const ROUTES = {
  LOGIN: "/login",
  HOME: "/",
  RESULT: "/result",
  ABOUT: "/about",
  CONTACT: "/contact",
  BRANCH: "/branches",
  MENU: "/menu",
  FOODDETAIL: "/menu/:slug",
  CART: "/cart",
  COMPLETEINFO: "/completeInfo",
  PAYMENT: "/payment",
  SUCCESSFULPAYMENT: "/successfulPayment",
  CONTACT: "/contact",
  FAQ: "/faq",
  PRIVACY: "/privacy",
  RULES: "/rules",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  ORDERHISTORY: "/orderHistory",
  FAVORITES: "/favorites",
  ADDRESS: "/address",
};

export default ROUTES;
